---
global:
  scrape_interval: '5s'
# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"
# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'localhost:9090'

  - job_name: 'vms'
    static_configs:
      - targets:
        - 'prom-01:9100'
        - 'db-01:9100'
        - 'db-02:9100'
        - 'etcd-01:9100'
        - 'etcd-02:9100'
        - 'etcd-03:9100'
        - 'balancer-01:9100'

  - job_name: 'postgres'
    static_configs:
      - targets:
        - db-01:5432
        - db-02:5432 
  
  - job_name: 'patroni'
    static_configs:
      - targets:
        - db-01:9547
        - db-02:9547 
  
  - job_name: 'blackbox'
    # scheme: http
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://9f5f69f6-aa8c-4658-abf1-f6deeb4ebbba.mts-gslb.ru/cities/    # Target to probe with http.
        - http://9f5f69f6-aa8c-4658-abf1-f6deeb4ebbba.mts-gslb.ru/WeatherForecast/    # Target to probe with http.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115  # The blackbox exporter's real hostname:port